dist: trusty
sudo: required

language: minimal

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.19.0

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - sudo rm -rf /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin/
  - sudo apt-get -q update
  - sudo apt-get install -qy make apt-transport-https ca-certificates curl software-properties-common gawk jq parallel

before_script:
  - uname -a
  - type -a docker-compose && docker-compose version
  - docker version

script:
  - git fetch --unshallow && git tag -l
  - make -f Makefile.deploy build-all-images
  - make -f Makefile.deploy up-all
# create test env
  - make -f Makefile.deploy wait-elasticsearch
  - make -f Makefile.deploy index-create
  - make -f Makefile.deploy index-status
  - make -f Makefile.deploy test-up
# teardown
  - make -f Makefile.deploy down-all

after_script:
  - make -f Makefile.deploy build-dir-clean
