version: '2'

# this docker configuation intends to build frontend
# it is supposed that your declared some ENV variables:
#   - ${FRONTEND} points to ${APP} frontend

services:
  build-frontend:
    build:
      context: ${FRONTEND}
      dockerfile: Dockerfile.build
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
        npm_registry: ${NPM_REGISTRY}
        sass_registry: ${SASS_REGISTRY}
        MIRROR_DEBIAN: ${MIRROR_DEBIAN}
        app_path: /${APP}
        app_name: ${APP}
        app_ver: ${APP_VERSION}
    image: ${APP}-frontend:${APP_VERSION}
    environment:
      - APP=${APP}
      - APP_VERSION=${APP_VERSION}
    container_name: ${APP}-build-front
    volumes:
      - ${FRONTEND}/index.html:/${APP}/index.html
      - ${FRONTEND}/.babelrc:/${APP}/.babelrc
      - ${FRONTEND}/.editorconfig:/${APP}/.editorconfig
      - ${FRONTEND}/.eslintignore:/${APP}/.eslintignore
      - ${FRONTEND}/.eslintrc.js:/${APP}/.eslintrc.js
      - ${FRONTEND}/${APP}Config:/${APP}/${APP}Config/
      - ${FRONTEND}/config:/${APP}/config/
      - ${FRONTEND}/src:/${APP}/src/
      - ${FRONTEND}/build:/${APP}/build/
      - ${FRONTEND}/static:/${APP}/static/
      - ${FRONTEND}/dist-build:/${APP}/dist/
