version: '2'

services:
  backend:
    build:
      context: ${BACKEND}
      args:
        proxy: ${http_proxy}
        app_path: /${APP}
        app_name: ${APP}
    image: ${APP}-backend:latest
    container_name: ${APP}-backend
    volumes:
      - ${BACKEND}/code/:/${APP}/code/
      - ${BACKEND}/conf/:/${APP}/conf/
      - ${BACKEND}/log:/log/
      - ${BACKEND}/upload:/upload/

    restart: always

networks:
  default:
    external:
      name: ${APP}
