version: '2'

services:
  kibana:
    image: kibana:latest
    container_name: ${APP}-kibana
    volumes:
      - ${BACKEND}/kibana/config/:/usr/share/kibana/config
    # ports:
    #   - "5601:5601"

networks:
  default:
    external:
      name: ${APP}
            