version: '2'

networks:
  default:
    external:
      name: ${APP}

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.2
    container_name: ${APP}-elasticsearch
    environment:
      - cluster.name=${APP}
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 4g
    volumes:
      - ${ES_PATH}:/usr/share/elasticsearch/data
    # ports:
    #   - 9200:9200


