version: '2'

services:
  postgres:
    image: postgres:10
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: matchid 
    mem_limit: 2g
    volumes:
      - ${BACKEND}/pgdata:/var/lib/postgresql/data
    # ports:
    #   - 5432:5432

networks:
  default:
    external:
      name: matchid
